import {useState} from 'react';
import {call} from './api';
export type Place={place_id:string;name:string;category:string;address:string;distance_m:number;map_url:string;directions_url:string};
export type NearbyData={policy_search_url:string;event_id:number;event_title:string;event_time:string|null;venue_name:string;status:string;reason?:string;places:Place[];source:string;fetched_at:string;limits:string;radius_m:number};
const categories=['parking','restaurant','bar'] as const;
const labels={parking:'Park once',restaurant:'Dinner nearby',bar:'An optional drink'};
export function NearbyPlan({data}:{data:NearbyData}){
  const [choices,setChoices]=useState<Record<string,string>>({});
  if(data.status!=='ok')return <p className="fine">{data.reason}</p>;
  const stop=(category:typeof categories[number])=>{
    const places=data.places.filter(p=>p.category===category),chosen=places.find(p=>p.place_id===choices[category]);
    return <article className="night-stop" key={category}><p className="eyebrow orange">{labels[category]}</p><label>Choose a {category==='restaurant'?'restaurant':category==='parking'?'parking option':'bar'}<select value={choices[category]||''} onChange={e=>setChoices({...choices,[category]:e.target.value})}><option value="">{places.length?'Choose or skip this stop':'No listings in this radius'}</option>{places.map(p=><option key={p.place_id} value={p.place_id}>{p.name} · {p.distance_m} m</option>)}</select></label>{chosen&&<><h3>{chosen.name}</h3><p>{chosen.address}</p><p className="fine">{chosen.distance_m} m from the venue · straight-line distance</p><div className="buttons"><a href={chosen.map_url} target="_blank" rel="noreferrer">Check listing ↗</a><a href={chosen.directions_url} target="_blank" rel="noreferrer">Walk to venue ↗</a></div></>}{category==='parking'&&<p className="fine">Check public access, closing time, rates, and space availability before parking.</p>}{category==='bar'&&<p className="fine">After the show, if open. Event end time is not supplied.</p>}</article>;
  };
  return <div className="night-plan"><h3>Your night, around {data.venue_name}.</h3><p className="fine">Pick your stops. Nearby options make a park-once plan possible; check the walking routes before deciding.</p>{stop('parking')}{stop('restaurant')}<article className="night-stop event-stop"><p className="eyebrow orange">The main event</p><h3>{data.event_title}</h3><p>{data.venue_name}</p><p>{data.event_time?.replace('T',' · ')||'Time to be confirmed'} · venue local time</p></article>{stop('bar')}<article className="night-stop"><p className="eyebrow orange">Before you leave</p><h3>Bag policy & prohibited items</h3><p className="fine">Policy not yet confirmed. Check the official venue or event page for bag size, clear-bag rules, and prohibited items.</p><a href={data.policy_search_url} target="_blank" rel="noreferrer">Find the venue’s official policy ↗</a></article><p className="fine">Listings: {data.source} · retrieved {new Date(data.fetched_at).toLocaleString()} · search radius {data.radius_m} m.</p><p className="fine">{data.limits} These listings are separate from the event fact verification.</p></div>;
}
export default function Nearby({eventId}:{eventId:number}){
  const [data,setData]=useState<NearbyData|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[radius,setRadius]=useState(1200);
  async function search(){setBusy(true);setError('');setData(null);try{setData(await call<NearbyData>('nearby_places',{event_id:eventId,category:'all',radius_m:radius}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="nearby"><p className="eyebrow orange">MAKE A NIGHT OF IT</p><h3>Park once. Enjoy the night.</h3><div className="buttons"><label>Search radius <select value={radius} onChange={e=>setRadius(Number(e.target.value))}><option value={600}>600 m</option><option value={1200}>1.2 km</option><option value={2500}>2.5 km</option></select></label><button disabled={busy} onClick={search}>{busy?'Finding nearby places…':'Find parking, dinner & drinks →'}</button></div>{error&&<p role="alert">{error}</p>}{data&&<NearbyPlan key={data.fetched_at} data={data}/>}</section>;
}
